### ISSUE TITLE
Guidance on setting up the API service locally

### ISSUE THREAD

**Issue by bsriramulu** [angular-in-action/api#1]
I have limited internet access and therefore would like to host API locally for learning purposes. Please provide the guidance and necessary code files to setup the API service locally. Thanks.

**Comment by gnomeontherun** [comment]
Running this server locally still requires internet connection, because it connects to remote services. Unfortunately I didn't design this API to run any other way, because stock prices must come across the internet. If you have a limited connection, I suggest the best way to handle this is to download a snapshot of the data once as a JSON file, then update your demo to load from the local JSON file. You get static data, but it can run without the API.

However, here are the basic instructions.

* Clone the repository and navigate to it
* Run `npm install`
* Create a Firebase account if you don't have one (Google cloud console)
* Create a new project
* Find the API key and details in your project settings
* Create a `.env` file at the root of the repo and add properties by name (see https://github.com/angular-in-action/api/blob/master/index.js#L26)
* Run `npm start` and you should be up and running
* Update any references to the API to your new URLs

**Comment by gnomeontherun** [comment]
I've updated this service to be fully independent of the details above, just set it up and run it locally based on the README details.
